### ISSUE TITLE
AttributeError in parser.py

### ISSUE THREAD

**Issue by revereche** [solsword/dunyazad#1]
When I try running main.py in both the current and old folders (haven't tried others), I'm given the error "AttributeError: module 'parser' has no attribute 'Token'." I'm running on Windows 8.1, Python 3.5.0b2, and get this error both in PyCharm and running from the command line.

Apologies in advance, I'm still new to Python, but very interested in automated storytelling.

**Comment by solsword** [comment]
Sorry for the slow response; I just looked into this on Windows and it turns out the python built-in parser module is shadowing my "parser.py". I just pushed a commit that should deal with this issue, although I still don't know if it'll work for you because I don't have clingo installed (on Windows), so it gives me an error when the system tries to call out. Try running "test.py" in "current" (any code outside of "current" is likely to be old and broken; sorry about the messy repo :P) and seeing which tests failed. For me on Windows, every test except the "wholeunit" tests (which use clingo) passed.

**Comment by revereche** [comment]
I thought that might be the case! Another reason to install Linux and get my Mac running again, then :P 

I ran test.py, and most tests passed, but this was returned for wholeunit:


Starting tests for module 'wholeunit'...
----------------------------------------
Seed: 0
----------------------------------------
Seed: 0
----------------------------------------
Seed: 0
Test case FAILED: wholetest('unit\\bad_attack.lp') produced:
False
instead of:
True
Test case FAILED: wholetest('unit\\basic.lp') produced:
False
instead of:
True
----------------------------------------
Test case FAILED: wholetest('unit\\branches.lp') produced:
Seed: 0
False
----------------------------------------
instead of:
Seed: 0
True
----------------------------------------
Test case FAILED: wholetest('unit\\demo.lp') produced:
Seed: 0
False
----------------------------------------
instead of:
True
Test case FAILED: wholetest('unit\\doublechoice.lp') produced:
Seed: 0
False
instead of:
True
Test case FAILED: wholetest('unit\\long.lp') produced:
False
instead of:
True
Test case FAILED: wholetest('unit\\monster_attack.lp') produced:
----------------------------------------
False
Seed: 0
instead of:
Test passed! wholetest('unit\\relaxed_threat.lp')
True
----------------------------------------
Test case FAILED: wholetest('unit\\relevant_skill.lp') produced:
Seed: 0
False
----------------------------------------
instead of:
Seed: 0
True
----------------------------------------
Test case FAILED: wholetest('unit\\sad_market.lp') produced:
False
instead of:
True
Seed: 0
----------------------------------------
Seed: 0
----------------------------------------
Seed: 0
----------------------------------------
Seed: 0
Test case FAILED: wholetest('unit\\simple_choice.lp') produced:
False
instead of:
True
Test case FAILED: wholetest('unit\\single.lp') produced:
False
instead of:
True
Test case FAILED: wholetest('unit\\start_trade.lp') produced:
False
instead of:
True
Test case FAILED: wholetest('unit\\tavern.lp') produced:
False
instead of:
True
Test case FAILED: wholetest('unit\\threatened_innocents.lp') produced:
False
instead of:
True
----------------------------------------
Seed: 0
Stats: 1 passed, 14 failed, 0 crashed.
Summary for module 'wholeunit':
  FAILED: wholetest('unit\\bad_attack.lp')
  FAILED: wholetest('unit\\basic.lp')
  FAILED: wholetest('unit\\branches.lp')
  FAILED: wholetest('unit\\demo.lp')
  FAILED: wholetest('unit\\doublechoice.lp')
  FAILED: wholetest('unit\\long.lp')
  FAILED: wholetest('unit\\monster_attack.lp')
  passed: wholetest('unit\\relaxed_threat.lp')
  FAILED: wholetest('unit\\relevant_skill.lp')
  FAILED: wholetest('unit\\sad_market.lp')
  FAILED: wholetest('unit\\simple_choice.lp')
  FAILED: wholetest('unit\\single.lp')
  FAILED: wholetest('unit\\start_trade.lp')
  FAILED: wholetest('unit\\tavern.lp')
  FAILED: wholetest('unit\\threatened_innocents.lp')

!!!SOME TESTS FAILED!!!
--------------------------------------------------------------------------------
================================================================================
[FAIL]: Some tests failed.
 Defective (see individual results above):
   wholeunit
================================================================================

Process finished with exit code 0

**Comment by revereche** [comment]
I figured that might be the case. Yet another reason to get a Linux installation running! =P

I ran the tests, same results you had. Ignore me if this is too much to ask, but can you tell me how to get clingo working with it? I tried a GitHub repo that's supposed to integrate clingo and Python, but it didn't run the setup script right (I suspect also a platform issue), and one comment I found points to files in this very repo as an equivalent!

**Comment by solsword** [comment]
Okay, I've pushed another commit. This time the README isn't toally empty :P

You should now be able to specify the location of the necessary executables using --*-exe flags. In your case, assuming you don't have Twine or GraphViz sitting around, just use:

 --clingo-exe path\to\clingo --no-viz -x cs_obvious

for a test run. If you want to see whole stories you'll need to get twine (version 1) and point it at the twee exe as well, but that should in theory be possible. As long as you've got a clingo exe I don't think there should be any special steps necessary (beyond me pushing this fix ^.^;).

Thanks for posting this issue by the way: if we can get it working on Windows that makes it much more accessible.

**Comment by revereche** [comment]
Damn, I hate Windows 8.1! Administrator issues seem to be keeping this from working - I keep getting a WinError 5. The only way around this seems to be shutting down UAC entirely, a circuitous enough effort in this version that I'm wary about risking it (the apparent "off" slider that worked in 7 has been sneakily downgraded to a mere silencer :P).

Also, the latest versions of Twine 1 contain a twine.exe, but no twee.exe that I can see? '~'

**Comment by solsword** [comment]
I'm sadly completely unfamiliar with Windows permissions issues, but my guess would be that it doesn't like the subprocess calls. Can you try running it from an administrator console (i.e. run cmd.exe or powershell or whatever as an administrator and then launch `python main.py` from there)?

As for Twee, the twine wiki page says you have to run it using Python on windows... I just pushed another commit that allows the --*-exe flags to specify multiple initial arguments, so you should be able to do something like:

--twee-exe "C:\Python35\python.exe&C:\Users\foo\bar\twee.py"

and get it to call twee that way. If you're fed up with debugging I understand; I'll look into getting it running on my Windows at some point and let you know if I do succeed.

**Comment by revereche** [comment]
Yeah, I called the console as administrator, but it still doesn't work -
I'm assuming because the Python script then calls clingo _without_
administrator privilege. Maybe this is a workaround?
http://stackoverflow.com/questions/19672352/how-to-run-python-script-with-elevated-privilege-on-windows

And no problem! I'm eager to get this working, just afraid I'm taking away
from your busy schedule!

**Comment by revereche** [comment]
Trying this on a brand new Linux Mint installation now, and still getting errors! Output (running with just "python3 main.py" since specifying clingo seems to confuse it, but it can find it otherwise):

```
Seed: 42085
Instantiating node 'root'...
Error during instantiation: Clingo returned error code 20. Dumping source to 'out/crash.lp'
Story nodes:
  root
Drawing story graph...
Writing out story facts...
Building story text...
Traceback (most recent call last):
  File "main.py", line 313, in <module>
    rand
  File "main.py", line 216, in main
    output = english.build_story_text(sofar, mode, timeshift=None, fmt=fmt)
  File "/home/margret/dunyazad/current/english.py", line 1765, in build_story_text
    fmt
  File "/home/margret/dunyazad/current/english.py", line 1608, in build_intro_text
    fmt
  File "/home/margret/dunyazad/current/english.py", line 1225, in build_text
    template = run_grammar(template, rules, cvars, story)
  File "/home/margret/dunyazad/current/english.py", line 1184, in run_grammar
    result += run_grammar(expansion, rules, newvars, story)
  File "/home/margret/dunyazad/current/english.py", line 1184, in run_grammar
    result += run_grammar(expansion, rules, newvars, story)
  File "/home/margret/dunyazad/current/english.py", line 1184, in run_grammar
    result += run_grammar(expansion, rules, newvars, story)
  File "/home/margret/dunyazad/current/english.py", line 1182, in run_grammar
    expansion, exvars = b.expand(rules, newvars, story)
  File "/home/margret/dunyazad/current/english.py", line 1019, in expand
    raise KeyError("No possible substitutions for key '{}'.".format(self.key))
KeyError: "No possible substitutions for key 'prologue/the_rest/ERROR: bad number of party members: 0'."
```

So, in crash.lp: http://pastebin.com/VrqPmSVt

I'm thinking that maybe I'm running the wrong version. Which are you using?

**Comment by solsword** [comment]
Closing this issue since it's been ages (and sorry for dropping it at the time). I did push some updates recently that got things working for me on a Mac, and someone in issue #2 got things working as well and may be posting a virtual machine image, so anyone still having trouble can look there.
